apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: n1
  name: n1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n1
    spec:
      containers:
      - image: docker.io/siddharth67/nginx:1.0.4 # {"$imagepolicy": "flux-system:image-policy"}
        name: nginx
